spring:
  application:
    name: school
  datasource:
    url: jdbc:h2:mem:/Users/sid/database
    username: user
    password: user
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true